/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Test;

import edgedetection.CannyFilter;
import image.Image;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.JFrame;
import recognition.PuntiCefalometrici;

/**
 *
 * @author Yassin
 */
public class FrameEditImage extends javax.swing.JFrame {
    private static JFrame frameImage;
    private static Image img;
    private static Image edge;
    private static Image punti;
    /**
     * Creates new form FrameEditImage
     */
    public FrameEditImage(JFrame frameImage, Image img) {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        initComponents();
        edge = new Image();
        FrameEditImage.frameImage= frameImage;
        FrameEditImage.img = img;
        punti = new Image();
        this.setResizable(false);
        btnSearchPoints.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblLowThreshold = new javax.swing.JLabel();
        txtLowTreshold = new javax.swing.JTextField();
        lblHighThreshold = new javax.swing.JLabel();
        txtHighTreshold = new javax.swing.JTextField();
        btnEdgeDetection = new javax.swing.JButton();
        btnSearchPoints = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLowThreshold.setText("Low Threshold:");

        txtLowTreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLowTresholdActionPerformed(evt);
            }
        });

        lblHighThreshold.setText("High Threshold:");

        txtHighTreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHighTresholdActionPerformed(evt);
            }
        });

        btnEdgeDetection.setText("EDGE DETECTION");
        btnEdgeDetection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdgeDetectionMouseClicked(evt);
            }
        });
        btnEdgeDetection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdgeDetectionActionPerformed(evt);
            }
        });

        btnSearchPoints.setText("SEARCH POINTS");
        btnSearchPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchPointsMouseClicked(evt);
            }
        });

        jButton1.setText("<----   BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLowThreshold)
                            .addComponent(lblHighThreshold))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLowTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHighTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEdgeDetection, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(btnSearchPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowThreshold)
                    .addComponent(txtLowTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHighThreshold)
                    .addComponent(txtHighTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEdgeDetection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLowTresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLowTresholdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLowTresholdActionPerformed

    private void txtHighTresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHighTresholdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHighTresholdActionPerformed

    private void btnEdgeDetectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdgeDetectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdgeDetectionActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        FrameInterface frame = new FrameInterface();
        frame.setVisible(true);
        frameImage.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnEdgeDetectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdgeDetectionMouseClicked
        // TODO add your handling code here:
        
        frameImage.setVisible(false);
        float lowtreshold = Float.parseFloat(txtLowTreshold.getText());
        float hightreshold = Float.parseFloat(txtHighTreshold.getText());
        
        CannyFilter canny = new CannyFilter(lowtreshold,hightreshold);
        BufferedImage edges = canny.getBufferedImage(img);
        try {
            edge.loadImage(edges);
        } catch (IOException ex) {
            //Logger.getLogger(FrameEditImage.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameImage.setVisible(false);
        frameImage=edge.display();
        btnSearchPoints.setEnabled(true);
    }//GEN-LAST:event_btnEdgeDetectionMouseClicked

    private void btnSearchPointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPointsMouseClicked
        PuntiCefalometrici p = new PuntiCefalometrici("naso",1);
        frameImage.setVisible(false);
        try {
            punti = p.trovaPunti(edge,img);
        } catch (IOException ex) {
        }
        frameImage.setVisible(false);
        frameImage=punti.display();
        btnSearchPoints.setEnabled(false);
    }//GEN-LAST:event_btnSearchPointsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEditImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEditImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEditImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEditImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameEditImage(frameImage, img).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdgeDetection;
    private javax.swing.JButton btnSearchPoints;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblHighThreshold;
    private javax.swing.JLabel lblLowThreshold;
    private javax.swing.JTextField txtHighTreshold;
    private javax.swing.JTextField txtLowTreshold;
    // End of variables declaration//GEN-END:variables
}
